### ISSUE TITLE
Resolution of any blockchain tld is unavailable

### ISSUE THREAD

**Issue by JustOff** [B-DNS/Firefox#2]
I always get the message that resolution of blockchain tld is unavailable.

Manual check shows that bdns.bz does not respond to resolve requests - connection is always timed out.

**Comment by astanze** [comment]
Sorry, there were some problems while I was upgrading the servers. It should be fine now, if not - do let me know and I'll look into it.

**Comment by JustOff** [comment]
Now the error is: "bdns.co:443 uses an invalid security certificate. The certificate is not trusted because it is self-signed."

**Comment by astanze** [comment]
One of the domains used a self-signed certificate. Check again please, now everything should work.

**Comment by JustOff** [comment]
Now it works. However `The referenced resource will be unavailable until you reload this page.` message I got every time I visit new domain is pretty annoying.

**Comment by astanze** [comment]
> However The referenced resource will be unavailable until you reload this page. message I got every time I visit new domain is pretty annoying.

This should not happen. Does it still occur? If so which domain are you trying to browse that brings up this message?

The meaning is that in Firefox it's impossible to catch requests to embedded .bit/other resources into normal pages (see #1 for an example). Those must be quire rare so normally this message should not appear.
